/*
 * LiveButtons+
 * @author: Ethan Lin, Mike Kellum
 * @uri: https://github.com/oel-mediateam/lbplus
 * @version: 0.0.1 (alpha)
 * @license: The Artistic License 2.0
 *
 * Copyright (c) 2015 University of Wisconsin-Extension,
 * Divison of Continuing Education, Outreach & E-Learning
 *
*/
function onYouTubeIframeAPIReady(){video.player=new YT.Player(video.selector,{width:"649",height:"360",videoId:video.vId,playerVars:{autoplay:0,controls:0,disablekb:1,enablejsapi:1,iv_load_policy:3,loop:0,modestbranding:1,rel:0,showinfo:0},events:{onReady:onPlayerReady,onStateChange:onPlayerStateChange}})}function onPlayerReady(){var e=video.player.getDuration();e=1e3*e,e=moment(e).format("mm:ss"),$(".progress_bar .time .duration").html(e),loadCustomYouTubeEvents()}function onPlayerStateChange(e){var t=["ended","playing","paused","buffering",,"video cued"],o=null;o=-1===e.target.getPlayerState()?"unstarted":t[e.target.getPlayerState()],$(".dev-log").append(o+"<br />")}function loadCustomYouTubeEvents(){$("#videoPlayBtn").on("click",function(){$(this).remove(),video.player.playVideo(),$("#stopVideoBtn").removeAttr("disabled")})}var soundEffects={click:"click",powerUp:"power_up",odd:"no_mercy"},video={player:null,selector:"ytv",vId:null};$(document).ready(function(){$.fn.loadSoundEffects(),video.vId=$("#"+video.selector).attr("data-videoId"),$.fn.loadYouTubeAPI();for(var e=0;e<$(".btn[data-action]").length;e++)$(".btn[data-action]:eq("+e+")").clicked();$(".progress_bar").progress()}),$.fn.loadSoundEffects=function(){$.each(soundEffects,function(e,t){var o=t;soundEffects[e]=document.createElement("audio"),soundEffects[e].setAttribute("src","sounds/"+o+".mp3")})},$.fn.loadYouTubeAPI=function(){var e=document.createElement("script"),t=document.getElementsByTagName("script")[0];e.src="https://www.youtube.com/iframe_api",t.parentNode.insertBefore(e,t)},$.fn.clicked=function(){$(this).on("click",function(){$(this).hasClass("disabled")||($(this).hasClass("odd")?soundEffects.odd.play():soundEffects.powerUp.play(),$(this).cooldown(),$(".dev-log").append($(this).attr("data-action")+" @ "+1e3*video.player.getCurrentTime()+" <br />"))})},$.fn.cooldown=function(){var e=$(this).index(".btn"),t=$(this),o=t.width(),n=1e3*Number(t.attr("data-cooldown")),a=t.find(".cooldown .progress"),d=$(a.selector+":eq("+e+")");d.width()>=o&&(d.width(0),t.addClass("disabled")),d.animate({width:o},n,function(){t.removeClass("disabled")})},$.fn.progress=function(){var e=$(this),t=e.width(),o=e.find(".progressed"),n=$(o.selector);n.animate({width:t},3e4)},$.fn.showTransition=function(e,t){$(this).prepend('<div class="transition_overlay"><div class="heading">'+e+'</div><div class="subheading">'+t+'</div><div class="loading"><span class="icon-spinner spin"></span></div></div>'),$(".transition_overlay").css("display","none").fadeIn()},$.fn.hideTransition=function(){$(".transition_overlay").fadeOut(function(){$(this).remove()})};
//# sourceMappingURL=./lbplus.js.map